### PR TITLE
Fixing issues with v2-dev including union and sub-queries.

### PR DESCRIPTION
**Pull request by kwhat**
Fixes issues with SELECT `*` and `table.column`.

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
What would happen with columns which clash with SQL key words and functions in this case?

**Comment by kwhat** [comment]
@Caffe1neAdd1ct user can manually escape in the query.  The current escape is not quite correct as it should do 'table'.'column' instead of 'table.column'.  I may go back and fix that if I can find a clean way to get it done.

**Comment by Caffe1neAdd1ct** [comment]
Good point, that would be fine.

However inside backticks I think full stop characters are allowed, at least
in MySQL...

If not quoted with backticks already by the user, splitting on the full
stop then quote on the 2 identifiers, if already quoted.. leave alone?

**Comment by kwhat** [comment]
@Caffe1neAdd1ct yah I'm working though it right now.  Should have an update shortly.

**Comment by kwhat** [comment]
I have removed the back-ticks as the current approach is very broken.  I have also added union support to select and sub-query support in various places.

**Pull request merged**
