### PR TITLE
Added support for managing MariaDB users

### PR DESCRIPTION
**Pull request by alvarengacarlos**
The purpose of the implementation is to facilitate the automation of the database user administration process. I just implemented MariaDB because it was what I needed at the time. 

I am not an experienced programmer. That is why people apologize if there is a mistake.

### CODE REVIEW

**Comment by kwhat** [comment]
Thanks for the pull request.  Unfortunately I will not be able to merge this into 2.x as I am working on 3.x which will include a support for PostgreSQL and Microsoft SQL Server.  I would suggest opening a pull request against [3.0](https://github.com/kwhat/PDO/tree/3.0) and making sure all of the tests and linting passes.

**Comment by alvarengacarlos** [comment]
> Thanks for the pull request. Unfortunately I will not be able to merge this into 2.x as I am working on 3.x which will include a support for PostgreSQL and Microsoft SQL Server. I would suggest opening a pull request against [3.0](https://github.com/kwhat/PDO/tree/3.0) and making sure all of the tests and linting passes.

Thanks for answering. So I must close this pull request?

**Comment by kwhat** [comment]
No need to close, I still have a lot of work to do in 3.0.  It's going to take some significant refactoring to get things playing nicely together.  You can just leave this open and ill figure it out in a while.

**Comment by kwhat** [comment]
Merging to a development branch were I can start integrating this.

**Pull request merged**
