### PR TITLE
Add Update on Duplicate Key Functionality

### PR DESCRIPTION
**Pull request by techjwalker**
PR on behalf of @shaq127 to add functionality.

Resolves issue https://github.com/FaaPz/Slim-PDO/issues/86 and https://github.com/FaaPz/Slim-PDO/issues/72

Tested and seems to function as intended.

EDIT: Self-closed because this sat for a year without any dev response.

### CODE REVIEW

**Comment by techjwalker** [comment]
Updated docs for the added functionality, with example.

**Comment by dfelix** [comment]
It would be great to have this functionality! :)

**Comment by kwhat** [comment]
why was this closed?  I cannot reopen...

**Comment by kwhat** [comment]
@techjwalker If you wan't credit, please reopen against 2.x

**Pull request closed without merging**
